name: Deploy to GH Pages

on: 
  push:
    branches:
      - master
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BASE_PATH: html-editor
    steps:
      - name: Checkout 
        uses: actions/checkout@v2.3.4

      - name: Install and build
        run: |
          npm install
          npm run build
      
      - name: Add .nojekyll
        run: |
          touch dist/.nojekyll
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist

